version: '3'

services:
  my_redis:
    image: redis:latest
    ports:
      - 6379:6379
  ddingji-world-api:
    image: kgh2120/ddingji-world:1.0.0
    ports:
      - 8080:8080
    depends_on:
      - my_redis
