spring:
  datasource:
    url:  jdbc:h2:~/test
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: true
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /h2-console