spring:
  datasource:
    url:  jdbc:h2:mem:test;MODE=mysql;
    driverClassName: org.h2.Driver
    username: sa
    password:
    hikari:
      connection-timeout: 5000 #timeout 5sec.
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      encoding: utf-8
  cache:
    type: redis
    redis:
      cache-null-values: true
  data:
    redis:
      host: localhost
      port: 6379
