### GET 전체 레스토랑 데이터
GET http://localhost:8080/restaurants

### GET 한식 카테고리 레스토랑 데이터
GET http://localhost:8080/restaurants?category=korean

### GET 잘못된 카테고리 요청 예외 처리
GET http://localhost:8080/restaurants?category=invalid

### GET 레스토랑 ID 조회
GET http://localhost:8080/restaurants/1